{% macro get_treasure_columns() %}

{{ return(['TRANS_NUMBER_18N_2021_PROCESSALL_FUNDRAISINGALL',
            'TRANS_ACCOUNTINGDATE_18N_2021_PROCESSALL_FUNDRAISINGALL',
            'TRANS_CAMPAIGNYEAR_18N_2021_PROCESSALL_FUNDRAISINGALL',
            'TRANS_CAMPAIGNTYPE_18N_2021_PROCESSALL_FUNDRAISINGALL',
            'TRANS_TOTALPLEDGEAMT_18N_2021_PROCESSALL_FUNDRAISINGALL',
            'TRANS_TYPE_18N_2021_PROCESSALL_FUNDRAISINGALL',
            'TRANS_UDF01_18N_2021_PROCESSALL_FUNDRAISINGALL_SPECIALEVENTDESCRIPTION',
            'TRANS_UDF02_18N_2021_PROCESSALL_FUNDRAISINGALL_GIKDESCRIPTION',
            'TRANS_UDF03_18N_2021_PROCESSALL_FUNDRAISINGALL_PAYMENTINFORMATION',
            'TRANS_UDF04_18N_2021_PROCESSALL_FUNDRAISINGALL_REVENUESOURCE',
            'TRANS_UDF06_18N_2021_PROCESSALL_FUNDRAISINGALL_SPONSORSHIPINFORMATION']) }}

{% endmacro %}
-- treasure = 