{% macro get_to_be_dropped_columns() %}

{{ return('ADR_IND_11005_ADDRESSLINE1,
            ADR_IND_11005_ADDRESSLINE2,
            ADR_IND_11005_ADDRESSLINE3,
            ADR_IND_11005_CITY,
            ADR_IND_11005_STATEORPROV,
            ADR_IND_11005_ZIPPOSTALCODE,
            ADR_IND_WORK_ADDRESSLINE1,
            ADR_IND_WORK_ADDRESSLINE2,
            ADR_IND_WORK_ADDRESSLINE3,
            ADR_IND_WORK_CITY,
            ADR_IND_WORK_STATEORPROV,
            ADR_IND_WORK_ZIPPOSTALCODE,
            ADR_ORG_11005_ADDRESSLINE1,
            ADR_ORG_11005_ADDRESSLINE2,
            ADR_ORG_11005_ADDRESSLINE3,
            ADR_ORG_11005_CITY,
            ADR_ORG_11005_STATEORPROV,
            ADR_ORG_11005_ZIPPOSTALCODE,
            EMA_IND_PERSONAL_EMAILADDRESS,
            EMA_IND_WORK_EMAILADDRESS,
            EMA_ORG_BUSINESS_EMAILADDRESS,
            PHN_IND_HOME_FORMATTEDPHONE,
            PHN_IND_CELL_FORMATTEDPHONE,
            PHN_IND_WORK_FORMATTEDPHONE,
            PHN_IND_CW_FORMATTEDPHONE,
            PHN_ORG_BUS_FORMATTEDPHONE') }}

{% endmacro %}
-- to_be_dropped = 