{% macro get_eventAttendees_columns() %}

{{ return('ATTENDANCE_IND_ALL_ALL_ALL_EVENTACCOUNT,
            ATTENDANCE_IND_ALL_ALL_ALL_EVENTNAME,
            ATTENDANCE_IND_ALL_ALL_ALL_OCCURRENCE,
            ATTENDANCE_IND_ALL_ALL_ALL_STARTDATE,
            ATTENDANCE_IND_ALL_ALL_ALL_STARTTIME,
            ATTENDANCE_IND_ALL_ALL_ALL_ENDDATE,
            ATTENDANCE_IND_ALL_ALL_ALL_ENDTIME,
            ATTENDANCE_IND_ALL_ALL_ALL_EVENTCLASS,
            ATTENDANCE_IND_ALL_ALL_ALL_WEBDESCRIPTION,
            ATTENDANCE_IND_ALL_ALL_ALL_ATTENDANCETYPE') }}

{% endmacro %}
